### ISSUE TITLE
Implement 12h complete rebroadcast of IPNS records to the DHT

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/w3name#5]
### Context:

w3name will be rebroadcasting IPNS requests every 24 hours to the DHT, so users don't have to do it.

### Scope of this ticket:

* Setup alarm inside Durable Object instance
* Create alarm handler
  * Reschedule alarm for the next 24 hours
  * POST rebroadcast request to ipns-publisher
* Add tests

### Acceptance criteria:

- [ ] As a user, my IPNS records are rebroadcasted to the DHTs every 24 hours

**Comment by mbommerez** [comment]
We might need to split this one in 2 parts:
- [ ] work to do on API
- [ ] work to on IPNS publisher

**Comment by alanshaw** [comment]
I talked this over with François, alarms are IMO a bit risky - I don't know what happens when you migrate the DO to a new version - all existing instances and (I assume) alarms would be cleared out an we'd need a way to reinstantiate.

I'm not super keen on cron state but I do believe a cron is the simpliest thing that we can do to get this working that would allow us to publish around 5,000,000 IPNS keys (which should keep us going for a while). So specifically:

1. Create a cron that triggers every 12 hours
1. Query DO storage to fetch a page of 10,000 items
1. POST to a batch ipns-publisher endpoint for publishing records
1. Goto 2

You get 1,000 subrequests, so you can do ~5,000,000 records (1,000 * 10,000 / 2). Could could squeeze more out by batching up more than the page size.

**Comment by alanshaw** [comment]
Ok so why don't we do 4 (alarms) but first we need to:

1. Check that when a DO migration occurs that alarms remain intact.

If they don't then we need:
* A script that exports all current IPNS records
    * By listing all objects (object ID should be IPNS key)
    * Calls `GET /name/:key` to get the current IPNS record
* Then we can deploy a new version (and migrate DOs)
* Call `POST /name/:key` with the current record for each record
* ...to reinstantiate all DO's and alarms

**Comment by francois-potato** [comment]
I can confirm:

- alarms are not reset when doing a migration (for example a [renamed_classes migration](https://developers.cloudflare.com/workers/learning/using-durable-objects#configuring-durable-object-classes-with-migrations))
- alarms are not reset when deploying a new version

I tested this with a DO that updates a counter every minute. After a class migration and deploying new versions, the counter was never reset to zero.

It was also possible to cancel an alarm by deploying a new alarm handler that did not reschedule an alarm and did no operation.

```js
export class AlarmCounter2 {
  state: DurableObjectState
  env: Env

  constructor (state: DurableObjectState, env: Env) {
    this.state = state
    this.env = env
  }

  async fetch (request: Request) {
    const currentAlarm = await this.state.storage.getAlarm()
    const alarmIsActive = Boolean(currentAlarm)
    if (currentAlarm === null) {
      await this.state.storage.setAlarm(Date.now() + 60 * SECONDS)
    }

    const value: Number | undefined = await this.state.storage.get('value')

    const data = {
      alarmIsActive,
      value,
      version: 3
    }

    return jsonResponse(JSON.stringify(data), 200)
  }

  async alarm () {
    const value: number | undefined = await this.state.storage.get('value')
    if (value === undefined) {
      await this.state.storage.put('value', 0)
    } else {
      await this.state.storage.put('value', value + 1)
    }

    await this.state.storage.deleteAlarm()
    await this.state.storage.setAlarm(Date.now() + 60 * SECONDS)
  }
}
```
