### ISSUE TITLE
Fix for Sentry and Logtail logging

### ISSUE THREAD

**Issue by francois-potato** [web3-storage/w3name#86]
- [x] Use a different environment for staging and production on Sentry
- [x] Use a different environment for staging and production on Logtail
- [x] Fix Sentry release value (there is a format error `release: Discarded invalid value @w3name/api-1.2.0`)

**Comment by adamalton** [comment]
[x] Use a different environment for staging and production on Sentry

This is already the case. It's just that we hadn't had any errors on staging, and so we'd never published anything to Sentry with `environment: 'staging'`, and Sentry just creates environments automatically as you use them. I've now triggered an error on staging, and so the 'staging' environment is now listed: Use a different environment for staging and production on Sentry

**Comment by adamalton** [comment]
* [x]  Fix Sentry release value (there is a format error release: Discarded invalid value @w3name/api-1.2.0)

This is a bit more fun…

The problem seems to be that we're trying to set it, but failing to, and so the Toucan library is setting it for us, but to a value which isn't valid. Allow me to elaborate…

In [buildworkermodule.mjs](https://github.com/web3-storage/w3name/blob/45d578bb8d7e2c577adffa975fce326e144ea118/packages/api/buildworkermodule.mjs#L19) we create a string of `w3name-api@${pkg.version}+${git.short(__dirname)}` and we attempt to set it as the value of the `SENTRY_RELEASE` environment variable. But that clearly isn't working, because the value that we see coming into Sentry is actually the default value which is [set by the Toucan library](https://github.com/robertcepa/toucan-js/blob/76fefe482b53091d87ea30b6fe298bb3d8e19839/packages/toucan-js/src/index.ts#L357-L362).

So the fix is to make the setting of the `SENTRY_RELEASE` environment variable work. The digging continues…

**Comment by francois-potato** [comment]
LGTM 👍
